# Generated by Django 4.1.3 on 2022-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='421-4212275_transparent-default-avatar-png-avatar-img-png-download.png', upload_to='profile_image'),
        ),
    ]
