# Generated by Django 4.1.3 on 2022-11-22 12:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('number_of_like', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0ae7545a-5514-4194-8411-fdb6edb29e49'), primary_key=True, serialize=False),
        ),
    ]
