# Generated by Django 4.1.3 on 2022-11-22 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_like_post_alter_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like_post',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='like_post',
            name='number_of_like',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('52150738-fae7-44a6-ace5-94cdd4fe8132'), primary_key=True, serialize=False),
        ),
    ]
