# Generated by Django 4.1.3 on 2022-11-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_rename_post_id_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Like_Post',
        ),
    ]
