# Generated by Django 4.1.3 on 2022-11-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_likepost_delete_like_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=500)),
            ],
        ),
    ]
